# Generated by Django 4.2 on 2023-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации фотографии'),
        ),
    ]
